In [1]:
import urllib.request
import os
import tarfile

In [2]:
url='http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz'
filepath='data/aclImdb_v1.tar.gz'
if not os.path.isfile(filepath):
    result=urllib.request.urlretrieve(url,filepath)
    print('download:',result)

In [3]:
if not os.path.exists('data/aclImdb'):
    tfile = tarfile.open('data/aclImdb_v1.tar.gz','r:gz')
    result=tfile.extractall('data/')

In [4]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [5]:
import re
def rm_tags(text):
    re_tag = re.compile(r'<[^>]+>')
    return re_tag.sub('',text)

In [6]:
def read_files(filetype):
    path = "data/aclImbd"
    file_list = []
    
    positive_path = path + '/' + filetype + '/pos/'
    for f in os.listdir(positive_path):
        file_list+=[positive_path+f]
        
    negative_path = path + '/' + filetype + '/neg/'
    for f in os.listdir(negative_path):
        file_list+=[negative_path+f]
    
    print('read',filetype, 'files:',len(file_list))
    
    all_labels = ([1] * 12500 + [0] * 12500)
    
    all_texts = []
    for fi in file_list:
        with open(fi, encoding = 'utf8') as file_input:
            all_texts += [rm_tags(" ".join(file_input.readlines()))]
    return all_labels, all_texts

In [7]:
y_train,train_text=read_files('train')

read train files: 25000


In [8]:
y_test,test_text=read_files('test')

read test files: 25000


In [9]:
print(train_text[0])
print(y_train[0])

There's been a spate of recent surfing movies that I seem to haphazardly run across without advance warning. I caught this treasure on digital cable this week and what a pleasant surprise it was! The focus is on the pioneers of big wave surfing from the 60's Greg Noll to our current Laird Hamilton, from Waimea Bay to Mavericks to Jaws. Hell, I could watch a movie just about Laird Hamilton - one of this generation's great athletes - so the rest is just gravy. There's loads of good surfing mixed in with interviews of past and present surfing stars, in pleasant, relaxed and unpretentious fashion. Of all the surfing movies I've seen this tells the big-wave story the best, and I think it's my favorite. Enjoy!
1


In [10]:
token = Tokenizer(num_words=3800)
token.fit_on_texts(train_text)
print(token.document_count)

25000


In [11]:
# print(token.word_index)
x_train_seq = token.texts_to_sequences(train_text)
x_test_seq = token.texts_to_sequences(test_text)

In [12]:
print(train_text[0])

There's been a spate of recent surfing movies that I seem to haphazardly run across without advance warning. I caught this treasure on digital cable this week and what a pleasant surprise it was! The focus is on the pioneers of big wave surfing from the 60's Greg Noll to our current Laird Hamilton, from Waimea Bay to Mavericks to Jaws. Hell, I could watch a movie just about Laird Hamilton - one of this generation's great athletes - so the rest is just gravy. There's loads of good surfing mixed in with interviews of past and present surfing stars, in pleasant, relaxed and unpretentious fashion. Of all the surfing movies I've seen this tells the big-wave story the best, and I think it's my favorite. Enjoy!


In [14]:
print(x_train_seq[0])

[221, 73, 3, 4, 1132, 98, 11, 9, 302, 5, 517, 633, 205, 1711, 9, 1056, 10, 19, 1874, 10, 1264, 2, 47, 3, 860, 8, 12, 1, 1144, 6, 19, 1, 4, 190, 35, 1, 5, 259, 35, 5, 5, 604, 9, 96, 102, 3, 16, 39, 40, 27, 4, 10, 83, 34, 1, 356, 6, 39, 221, 4, 48, 1845, 7, 15, 4, 497, 2, 975, 379, 7, 2, 1596, 4, 28, 1, 98, 203, 106, 10, 712, 1, 190, 61, 1, 114, 2, 9, 100, 41, 57, 510, 353]


In [13]:
x_train = sequence.pad_sequences(x_train_seq, maxlen=380)
x_test = sequence.pad_sequences(x_test_seq, maxlen=380)

In [14]:
print('before pad_sequences length=', len(x_train_seq[0]))
print(x_train_seq[0])

before pad_sequences length= 101
[221, 73, 3, 4, 1132, 98, 11, 9, 302, 5, 517, 633, 205, 1711, 9, 1056, 10, 2523, 19, 3534, 1874, 10, 1264, 2, 47, 3, 2203, 860, 8, 12, 1, 1144, 6, 19, 1, 4, 190, 2861, 35, 1, 3127, 5, 259, 2023, 35, 5, 5, 604, 9, 96, 102, 3, 16, 39, 40, 27, 4, 10, 83, 34, 1, 356, 6, 39, 221, 4, 48, 1845, 7, 15, 3007, 4, 497, 2, 975, 379, 7, 2203, 2, 1596, 4, 28, 1, 98, 203, 106, 10, 712, 1, 190, 2861, 61, 1, 114, 2, 9, 100, 41, 57, 510, 353]


In [15]:
print('after pad_sequences length=', len(x_train[0]))
print(x_train[0])

after pad_sequences length= 380
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0

In [16]:
from keras.models import Sequential
from keras.layers.core import Dense ,Dropout, Activation, Flatten
from keras.layers.embeddings import Embedding

model = Sequential()

#Add embedding layer
model.add(Embedding(output_dim=32,
                    input_dim=3800,
                    input_length=380))
model.add(Dropout(0.2))

In [17]:
model.add(Flatten())
model.add(Dense(units=256,
                activation='relu'))
model.add(Dropout(0.35))

In [18]:
model.add(Dense(units=1,
                activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 380, 32)           121600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 380, 32)           0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 12160)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               3113216   
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 257       
Total params: 3,235,073
Trainable params: 3,235,073
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
train_history = model.fit(x_train, y_train, batch_size=100,
                         epochs=10,verbose=2,
                         validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
 - 2s - loss: 0.4677 - acc: 0.7633 - val_loss: 0.5338 - val_acc: 0.7504
Epoch 2/10
 - 2s - loss: 0.1876 - acc: 0.9279 - val_loss: 0.5227 - val_acc: 0.7794
Epoch 3/10
 - 2s - loss: 0.0695 - acc: 0.9777 - val_loss: 0.5323 - val_acc: 0.8234
Epoch 4/10
 - 2s - loss: 0.0256 - acc: 0.9933 - val_loss: 0.8743 - val_acc: 0.7776
Epoch 5/10
 - 2s - loss: 0.0145 - acc: 0.9957 - val_loss: 0.8058 - val_acc: 0.8158
Epoch 6/10
 - 2s - loss: 0.0121 - acc: 0.9961 - val_loss: 0.9353 - val_acc: 0.8064
Epoch 7/10
 - 2s - loss: 0.0105 - acc: 0.9970 - val_loss: 1.0928 - val_acc: 0.7884
Epoch 8/10
 - 2s - loss: 0.0114 - acc: 0.9962 - val_loss: 0.9054 - val_acc: 0.8284
Epoch 9/10
 - 2s - loss: 0.0176 - acc: 0.9936 - val_loss: 1.1501 - val_acc: 0.7840
Epoch 10/10
 - 2s - loss: 0.0169 - acc: 0.9939 - val_loss: 1.3050 - val_acc: 0.7660


In [20]:
scores = model.evaluate(x_test, y_test, verbose=1)
scores[1]

25000/25000 [==============================] - 1s 44us/step


0.84176

In [25]:
predict=model.predict_classes(x_test)
predict[:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]], dtype=int32)

In [26]:
predict_classes=predict.reshape(-1)
predict_classes[:10]

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int32)

In [24]:
SentimentDict={1:'Positive',0:'Negative'}
def display_test_Sentiment(i):
    print(test_text[i])
    print('label real value:', SentimentDict[y_test[i]],
          'predicted value:', SentimentDict[predict_classes[i]] )

In [31]:
display_test_Sentiment(6)

The idea is not original... If you have seen such kind of story before, you would know what the ending would come out after watching for the first twenty minutes... the script, the positioning of the actors and the screening is too obvious... If you haven't seen such story before, it is definitely a good experience, you will enjoy the twist at the end...don't forget to watch it again after you know the "truth", you will even more enjoy the plots... Even though I have a right guess at the very beginning, I still couldn't help stick on my seat till the end...Conclusion: A must see!! This one from Korea is better than any recent movies of the genre from Japan...forget Hollywood!Don't miss it!!
label real value: Positive predicted value: Negative


In [21]:
input_text='''
Glass is truly a cinematic jewel, which closes the delicate and complex analysis begun by 
the two previous films.A journey to discover the inner strength (or weakness) that each of 
us has as a human being.Shyamalan directs this film, interpreted in an excellent way by all
the protagonists, without smearing and will surely disappoint all those people who will go 
to the cinema with the hope of seeing a cinecomics or an action movie.Glass tackles the 
mystery of souls and does so in an intelligent and almost delicate way. A truly excellent 
product, Cinema for high and sensitive minds. Show to reflect on our existence using 
archetypes and almost alchemical references. Suffice it to think of the continuous and 
stressed reference to number 3 or the events of the Ulysses of the Odyssey of which the 
film is full of quotations from the attentive spectator.Bravo, Shyamalan. Thank you so much 
for this wonderful spiritual journey veered only apparently in the world of comics. Standing 
Ovation.
'''

In [34]:
input_seq = token.texts_to_sequences([input_text])
print(input_seq)

[[6, 367, 3, 1356, 59, 1, 2, 1311, 30, 1, 103, 956, 104, 3, 1308, 5, 1969, 1, 38, 11, 253, 4, 174, 43, 13, 3, 402, 108, 10, 18, 7, 31, 317, 92, 30, 28, 1, 205, 2, 76, 1340, 28, 144, 80, 33, 76, 136, 5, 1, 434, 15, 1, 436, 4, 315, 3, 38, 31, 202, 16, 1, 731, 4, 2, 123, 34, 7, 31, 1086, 2, 216, 92, 3, 367, 317, 434, 14, 308, 2, 119, 5, 19, 259, 768, 2, 216, 8, 5, 100, 4, 1, 2, 5, 608, 339, 38, 1, 684, 4, 1, 4, 1, 4, 59, 1, 18, 6, 364, 4, 35, 1, 1294, 21, 34, 72, 14, 10, 385, 1308, 60, 682, 7, 1, 178, 4]]


In [35]:
len(input_seq[0])

125

In [37]:
pad_input_seq = sequence.pad_sequences(input_seq, maxlen=100)
len(pad_input_seq[0])

100

In [38]:
predict_result = model.predict_classes(pad_input_seq)

In [39]:
predict_result

array([[1]], dtype=int32)

In [41]:
SentimentDict[predict_result[0][0]]

'Positive'

In [22]:
def predict_review(input_text):
    input_seq = token.texts_to_sequences([input_text])
    pad_input_seq = sequence.pad_sequences(input_seq,maxlen=380)
    predict_result=model.predict_classes(pad_input_seq)
    print(SentimentDict[predict_result[0][0]])

In [25]:
predict_review(input_text)

Positive
